// Central icon registry. Components look up icons by string name so that
// data files (research.js, skills.js, projects.js) stay framework-agnostic.
import {
  FaWater,
  FaMountain,
  FaThermometerHalf,
  FaFlask,
  FaSatellite,
  FaTint,
  FaMapMarkedAlt,
  FaGlobeAmericas,
  FaGithub,
  FaLinkedin,
  FaGraduationCap,
  FaEnvelope,
  FaCode,
  FaDatabase,
  FaServer,
  FaReact,
  FaNodeJs,
  FaPython,
  FaDocker,
  FaGitAlt,
  FaLinux,
  FaJs,
  FaChartLine,
  FaBrain,
  FaLayerGroup,
  FaAws,
} from 'react-icons/fa';
import { SiTensorflow, SiPytorch, SiScikitlearn, SiExpress, SiMongodb, SiPostgresql, SiMysql, SiTypescript } from 'react-icons/si';

export const ICONS = {
  FaWater,
  FaMountain,
  FaThermometerHalf,
  FaFlask,
  FaSatellite,
  FaTint,
  FaMapMarkedAlt,
  FaGlobeAmericas,
  FaGithub,
  FaLinkedin,
  FaGraduationCap,
  FaEnvelope,
  FaCode,
  FaDatabase,
  FaServer,
  FaReact,
  FaNodeJs,
  FaPython,
  FaDocker,
  FaGitAlt,
  FaLinux,
  FaJs,
  FaChartLine,
  FaBrain,
  FaLayerGroup,
  FaAws,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiExpress,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiTypescript,
};

export function getIcon(name) {
  return ICONS[name] || FaCode;
}
